name: Build and Release Gem

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        working-directory: ./test
        run: ./.run.sh

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Build gem
        run: gem build asciidoctor-pdf-mathjax.gemspec

      - name: Publish gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem push *.gem

      - name: Create a Release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v0.1.1"
          release_name: "0.1.1"
          prerelease: false
