name: Build and Release Gem

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test and Build Gem
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Install Diff_PDF
        run: |
          # Install dependencies
          sudo apt-get update
          sudo apt-get install make automake g++
          sudo apt-get install libpoppler-glib-dev poppler-utils libwxgtk3.2-dev

          # Download diff-pdf code
          wget https://github.com/vslavik/diff-pdf/archive/refs/tags/v0.5.2.tar.gz -O diff-pdf-0.5.2.tar.gz \
            && tar -xzf diff-pdf-0.5.2.tar.gz \
            && rm diff-pdf-0.5.2.tar.gz

          # Build and install diff-pdf
          cd diff-pdf-0.5.2 \
            && ./bootstrap \
            && ./configure \
            && make \
            && sudo make install

      - name: Install Xvfb (artificial display server)
        run: sudo apt-get install xvfb

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 &   # Start Xvfb in the background
          echo "DISPLAY=:99" >> $GITHUB_ENV  # Set DISPLAY for subsequent steps

      - name: Run tests
        run: ruby test/test_*.rb

      - name: Build gem
        run: gem build *.gemspec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: '*.gem'
          name: gem

  release:
    name: Release Gem
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gem

      - name: Create a Release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v0.1.1"
          release_name: "0.1.1"
          prerelease: false

      - name: Publish gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: gem push *.gem
